[client]
showSidebarNavigation = false

[runner]
enforceSerializableSessionState = true

[theme]
primaryColor="#a2272c"
backgroundColor="#dbeefb"
secondaryBackgroundColor="#fff8ed"
textColor="#000000"
font="serif"
